Hw02
Ussuriec74/nodejs-homework-rest-api pull request #1
Opened 2022-10-29 17:08 UTC by Ussuriec74

Make home work #02

2022-10-31 17:23 UTC, Eastvarga commented on models/contacts.js
> +  return contacts;
Можна скорочувати запис не створюючи зайву змінну лише щоб її повернути в return : 
return JSON.parse(contactsRaw);

2022-10-31 17:25 UTC, Eastvarga commented on models/contacts.js
> +const addContact = async ({name, email, phone}) => {
Ви впевнені що вірно задаєте параметри функції? Тут помилка, спробуйте перевірити додаваня нового елементу, Треба виправити

2022-10-31 17:27 UTC, Eastvarga commented on routes/api/contacts.js
> +    console.log(contacts);
консоль елемент розробки, намагайтеся не залишати його не закоментованим, у робочому варіанті програми

2022-10-31 17:34 UTC, Eastvarga requested changes
Є декілька зауважень, одне з яких критичне.
Прошу усунути, сама робота добра

2022-10-31 18:39 UTC, Ussuriec74 commented on models/contacts.js
> +  return contacts;
fixed

2022-10-31 19:10 UTC, Ussuriec74 commented on models/contacts.js
> +const addContact = async ({name, email, phone}) => {
Виправив

2022-10-31 19:13 UTC, Ussuriec74 commented on routes/api/contacts.js
> +    console.log(contacts);
Виправив

2022-10-31 21:37 UTC, Eastvarga approved these changes

2022-10-31 21:37 UTC, merged

2022-11-04 09:49 UTC, Ussuriec74 reviewed
app.js