Hw03 mongodb
Ussuriec74/nodejs-homework-rest-api pull request #2
Opened 2022-11-06 13:05 UTC by Ussuriec74

2022-11-06 14:30 UTC, Eastvarga commented on controllers/contactController.js
> +      });
Цен не помилка, однак звідки у Вас любов до зайвої вкладеності?

2022-11-06 14:34 UTC, Eastvarga commented on controllers/contactController.js
> +  return next(createError(404, "Not found"));
Ви впевнені що розумієте як працює Ваш код? чому при невірному Айді повертаеться помилка бази даних?
CastError: Cast to ObjectId failed for value "6367c313bb187e1ff2c3e463q" (type string) at path "_id" for model "contacts"
    at model.Query.exec (D:\GoIt_Homeworks\HW_02\semko-valeriy\node_modules\mongoose\lib\query.js:4891:21) 
    at model.Query.Query.then (D:\GoIt_Homeworks\HW_02\semko-valeriy\node_modules\mongoose\lib\query.js:4990:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  messageFormat: undefined,
  stringValue: '"6367c313bb187e1ff2c3e463q"',
  kind: 'ObjectId',
  value: '6367c313bb187e1ff2c3e463q',
  path: '_id',
  reason: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
  Приведить код у порядок, бо він не працює так як ви гадаєте.

2022-11-06 14:35 UTC, Eastvarga commented on controllers/contactController.js
> +    return res.json({ data: { contact } });
Навкруги суцільна зайва вкладеність

2022-11-06 14:43 UTC, Eastvarga requested changes
Є зауваження, треба їх усунути

2022-11-07 07:32 UTC, Ussuriec74 commented on controllers/contactController.js
> +      });
Виправив, робив як у лекції

2022-11-07 08:45 UTC, Ussuriec74 commented on controllers/contactController.js
> +    return res.json({ data: { contact } });
Виправив

2022-11-07 08:45 UTC, Ussuriec74 commented on controllers/contactController.js
> +  return next(createError(404, "Not found"));
Ця база даних сама перевіряє id на відповідність її формату. Якщо id валідний, але об'єкта з id таким немає, то повертається "Not faund".

2022-11-09 18:34 UTC, Eastvarga approved these changes

2022-11-09 18:34 UTC, merged