Hw04 auth
Ussuriec74/nodejs-homework-rest-api pull request #3
Opened 2022-11-14 16:51 UTC by Ussuriec74

2022-11-14 19:15 UTC, Eastvarga commented on routes/api/authRouter.js
> +usersRouter.post("/logout", tryCatchWrapper(auth), tryCatchWrapper(authController.logoutUser));
Невірний метод для запиту. Що по завданню має бути?

2022-11-14 19:15 UTC, Eastvarga commented on routes/api/contactsRouter.js
> +contactsRouter.get("/:id", tryCatchWrapper(contactController.getContactById));
Забули ауторізацію перевірити у запита

2022-11-14 19:16 UTC, Eastvarga requested changes
Є зауваження

2022-11-15 07:55 UTC, Ussuriec74 commented on routes/api/authRouter.js
> +usersRouter.post("/logout", tryCatchWrapper(auth), tryCatchWrapper(authController.logoutUser));
Виправив, просто у лекції йде POST запит.

2022-11-15 07:56 UTC, Ussuriec74 commented on routes/api/contactsRouter.js
> +contactsRouter.get("/:id", tryCatchWrapper(contactController.getContactById));
Виправив

2022-11-15 17:22 UTC, Eastvarga approved these changes

2022-11-15 17:22 UTC, merged