Hw05 avatars
Ussuriec74/nodejs-homework-rest-api pull request #4
Opened 2022-11-21 16:35 UTC by Ussuriec74

2022-11-21 20:42 UTC, Eastvarga commented on controllers/userController.js
> +  return res.json({ status: "success" });
А яка повинна бути відповідь по ТЗ?

2022-11-21 20:43 UTC, Eastvarga requested changes
Є невеличке зауваження

2022-11-22 08:12 UTC, Ussuriec74 commented on controllers/userController.js
> +  return res.json({ status: "success" });
Виправив.

2022-11-22 13:59 UTC, Eastvarga approved these changes

2022-11-22 13:59 UTC, merged