make send email
Ussuriec74/nodejs-homework-rest-api pull request #5
Opened 2022-11-29 06:03 UTC by Ussuriec74

2022-11-29 19:49 UTC, Eastvarga requested changes
Є зауваження

2022-11-29 19:49 UTC, Eastvarga commented on controllers/userController.js
>        throw new Conflict("Email in use");
Погана реалізація перевірки дублювання.
Краще реалізувати через запит по пошті у базу, та, якщо юзер існує з такою поштою, відповісти помилкою

2022-11-29 19:49 UTC, Eastvarga commented on controllers/userController.js
> +  console.log(verificationToken);
не залишайте консолей у рабочому коді.

2022-11-29 19:49 UTC, Eastvarga commented on servises/emailServis.js
> +    from: "semko74@meta.ua",
Пошта відправника це теж змінний параметр, не треба його статично записувати - або у конфіг, або у змінні середовища

2022-11-30 17:21 UTC, Ussuriec74 commented on controllers/userController.js
>        throw new Conflict("Email in use");
Виправив. Тільки в цій гілці просто додалося надсилання посилання для підтвердження пошти.

2022-11-30 17:21 UTC, Ussuriec74 commented on controllers/userController.js
> +  console.log(verificationToken);
Вилучив

2022-11-30 17:21 UTC, Ussuriec74 commented on servises/emailServis.js
> +    from: "semko74@meta.ua",
Виправив

2022-11-30 20:02 UTC, Eastvarga approved these changes

2022-11-30 20:02 UTC, merged